remote_theme: giellalt/jekyll-theme-giellalt
title: Julev Sámi Text-to-Speech
description: Speech technology resources for the Julev Sámi language
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: minimal
